#!/usr/bin/bash
#
# Put customizations to your image in this file.

LOGSTASH_VERSION='1.4.2'
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Download and install logstash
echo "* Download and install logstash"
mkdir -p /opt/logstash
curl https://download.elasticsearch.org/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz | tar xz -C /opt/logstash --strip-components=1

# Enable mdata-setup script
echo "* Enable mdata-setup script"
svccfg import /tmp/mdata-setup.xml
rm /tmp/mdata-setup.xml

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
